### ISSUE TITLE
写的很好，后台也是自己写吗？

### ISSUE THREAD

**Issue by yunshuipiao** [yhlben/react-kandian#1]

**Comment by yhlben** [comment]
谢谢鼓励，后台是用爬虫爬的。 @yunshuipiao

**Comment by yunshuipiao** [comment]
@yhlben 好像不能访问了。后台用node.js吗？

**Comment by yhlben** [comment]
服务端问题，现在能访问了，后台php写的。用node也挺好的，使用一个node框架例如：express，koa，fastify，加上pm2部署，就行了。 @yunshuipiao
